### ISSUE TITLE
Arrumar o workflow de testes do repositório

### ISSUE THREAD

**Issue by vrtornisiello** [basedosdados/backend#815]
Os testes definidos no arquivo [.github/workflows/ci-python.yaml](https://github.com/basedosdados/backend/blob/01bee9124c549186746c899e1860705f83f6d051/.github/workflows/ci-python.yaml) estão falhando com o erro:

```shell
ModuleNotFoundError: No module named 'django'
```

Isso está acontecendo porque apenas as dependências de teste do pacote `backend` estão sendo instaladas.

```yaml
test:
    name: Test python
    runs-on: ubuntu-latest
    steps:
      # ... 
      - name: Install requirements
        run: poetry install --only=test
```

Para resolver o problema, precisamos substituir o comando `poetry install --only=test` pelo comando `poetry install --with test`, assim as dependências de teste são instaladas juntamente com o pacote `backend`. Além disso, mais configurações podem ser necessárias para que os testes possam ser executados.
